import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

import { menuItemsList } from '../src/utlis/menuItems.ts'
import type { NavigationCategory } from '../src/types/navigation.ts'

test('GitHub category includes both Chinese community resources', () => {
  const githubCategory: NavigationCategory | undefined = menuItemsList.find((category: NavigationCategory): boolean => category.name === 'GitHub')
  assert.ok(githubCategory?.tools)
  const resources = new Map(githubCategory.tools.map((tool) => [tool.id, tool]))

  assert.equal(resources.get('github-31')?.link, 'https://github-cn.com/')
  assert.equal(resources.get('github-32')?.link, 'https://gitcn.org/')
})

test('Terminal category includes macOS-like terminal resources', () => {
  const terminalCategory: NavigationCategory | undefined = menuItemsList.find((category: NavigationCategory): boolean => category.id === 26)
  assert.equal(terminalCategory?.name, '终端')
  assert.equal(terminalCategory?.icon, '⌨️')
  assert.ok(terminalCategory?.tools)

  const resources = new Map(terminalCategory.tools.map((tool) => [tool.id, tool]))
  assert.equal(resources.get('terminal-xtermjs')?.link, 'https://github.com/xtermjs/xterm.js')
  assert.equal(resources.get('terminal-iterm2')?.link, 'https://github.com/gnachman/iTerm2')
  assert.equal(resources.get('terminal-warp')?.type, 'terminal')
})

test('Terminal has a direct route that selects the terminal category', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/terminal'/)
  assert.match(appSource, /route\.path\s*===\s*'\/terminal'/)
  assert.match(appSource, /activeItem\.value\s*=\s*26/)
})

test('RunCode has a direct route and toolbox hub entry', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const toolboxSource = readFileSync(new URL('../src/views/toolbox/index.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/runcode'/)
  assert.match(routerSource, /views\/runcode\/index\.vue/)
  assert.match(routerSource, /path:\s*'\/toolbox'/)
  assert.match(routerSource, /views\/toolbox\/index\.vue/)
  assert.match(appSource, /goToolbox/)
  assert.match(toolboxSource, /\/terminal/)
  assert.match(toolboxSource, /\/runcode/)
})

test('Flash page loads real cnblogs status data instead of mock feeds', () => {
  const pageSource = readFileSync(new URL('../src/views/flash/index.vue', import.meta.url), 'utf8')
  const flashSource = readFileSync(new URL('../src/vue-pages-text-fn-abc/flash.ts', import.meta.url), 'utf8')
  const proxySource = readFileSync(new URL('../config/viteProxy.ts', import.meta.url), 'utf8')
  const resolverSource = readFileSync(new URL('../src/utils/resolveApiUrl.ts', import.meta.url), 'utf8')

  assert.match(pageSource, /function fetchFeeds\(\): Promise<void>/)
  assert.match(pageSource, /fetchOpenApiFeeds/)
  assert.match(pageSource, /fetchLegacyFeeds/)
  assert.match(pageSource, /isLoading/)
  assert.match(pageSource, /authRequired/)
  assert.match(pageSource, /真实接口/)
  assert.match(pageSource, /:class="\{ disabled: isLoading/)
  assert.match(pageSource, /博客园闪存真实接口需要登录态/)
  assert.doesNotMatch(pageSource, /reactive<FlashFeed\[\]>\(\[/)
  assert.doesNotMatch(pageSource, /mockFeed\('/)
  assert.match(flashSource, /buildFlashLegacyPath/)
  assert.match(flashSource, /buildFlashOpenApiPath/)
  assert.match(flashSource, /parseFlashLegacyHtml/)
  assert.match(flashSource, /parseFlashOpenApiData/)
  assert.match(flashSource, /FLASH_TOKEN_STORAGE_KEY = 'CNBLOGS_OPENAPI_TOKEN'/)
  assert.match(proxySource, /'\/api-cnblogs-ing': createProxyEntry\('\/api-cnblogs-ing', 'https:\/\/ing\.cnblogs\.com'/)
  assert.match(proxySource, /'\/api-cnblogs-openapi': createProxyEntry\('\/api-cnblogs-openapi', 'https:\/\/api\.cnblogs\.com'/)
  assert.match(resolverSource, /'\/api-cnblogs-ing': 'https:\/\/ing\.cnblogs\.com'/)
  assert.match(resolverSource, /'\/api-cnblogs-openapi': 'https:\/\/api\.cnblogs\.com'/)
})

test('Web Components has a direct route, navbar dropdown button, and component registry', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const wcSource = readFileSync(new URL('../src/views/webComponents/index.vue', import.meta.url), 'utf8')
  const registrySource = readFileSync(new URL('../src/components/webComponents/index.ts', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/web-components'/)
  assert.match(routerSource, /views\/webComponents\/index\.vue/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?\/web-components/)
  assert.match(noticeSource, /command="\/web-components"/)
  assert.match(wcSource, /customElements\.define/)
  assert.match(registrySource, /registerWebComponents/)
})

test('Oat UI has a direct route, navbar dropdown button, and 26 components showcase', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const oatSource = readFileSync(new URL('../src/views/oatUi/index.vue', import.meta.url), 'utf8')
  const oatRegistry = readFileSync(new URL('../src/components/oatUi/index.ts', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/oat-ui'/)
  assert.match(routerSource, /views\/oatUi\/index\.vue/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?\/oat-ui/)
  assert.match(noticeSource, /command="\/oat-ui"/)
  assert.match(oatSource, /ot-dropdown/)
  assert.match(oatSource, /ot-tag-input/)
  assert.match(oatRegistry, /registerOatUiComponents/)
})

test('Oat Studio provides update notice modal, new page modal, and confirm dialogs', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const studioSource = readFileSync(new URL('../src/views/oatStudio/index.vue', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/oat-studio'/)
  assert.match(routerSource, /views\/oatStudio\/index\.vue/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?\/oat-studio/)
  assert.match(noticeSource, /command="\/oat-studio"/)
  assert.match(studioSource, /OatUpdateModal/)
  assert.match(studioSource, /OatCreatePageModal/)
  assert.match(studioSource, /OatConfirmModal/)
  assert.match(studioSource, /OatDrawer/)
})

test('Auth Showcase provides 1,000,000 distinct interactive Login and Register UI themes switchable via Tabs', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const authSource = readFileSync(new URL('../src/views/authShowcase/index.vue', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/auth-showcase'/)
  assert.match(routerSource, /views\/authShowcase\/index\.vue/)
  assert.match(noticeSource, /command="\/auth-showcase"/)
  assert.match(authSource, /generate100wThemes/)
  assert.match(authSource, /glassmorphism/)
  assert.match(authSource, /cyberpunk/)
  assert.match(authSource, /theme-cat-mac/)
  assert.match(authSource, /theme-cat-neu/)
})

test('Cart Showcase and Animation Showcase provide 100 carts and 63,353 animations with dropdown entries', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const cartSource = readFileSync(new URL('../src/views/cartShowcase/index.vue', import.meta.url), 'utf8')
  const animSource = readFileSync(new URL('../src/views/animationShowcase/index.vue', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/cart-showcase'/)
  assert.match(routerSource, /path:\s*'\/animation-showcase'/)
  assert.match(routerSource, /path:\s*'\/motion-showcase'/)
  assert.match(routerSource, /path:\s*'\/schedule-x'/)
  assert.match(routerSource, /path:\s*'\/three-showcase\/china-map'/)
  assert.match(routerSource, /path:\s*'\/mapcn-showcase'/)
  assert.match(routerSource, /path:\s*'\/antv-s2-examples'/)
  assert.match(routerSource, /path:\s*'\/antv-g6-examples'/)
  assert.match(routerSource, /path:\s*'\/antv-f2-examples'/)
  assert.match(routerSource, /path:\s*'\/antv-l7-examples'/)
  assert.match(routerSource, /path:\s*'\/source-code'/)
  assert.match(routerSource, /path:\s*'\/docker-showcase'/)
  assert.match(noticeSource, /command="\/cart-showcase"/)
  assert.match(noticeSource, /command="\/animation-showcase"/)
  assert.match(noticeSource, /command="\/motion-showcase"/)
  assert.match(noticeSource, /command="\/schedule-x"/)
  assert.match(noticeSource, /command="\/three-showcase\/china-map"/)
  assert.match(noticeSource, /command="\/mapcn-showcase"/)
  assert.match(noticeSource, /command="\/antv-s2-examples"/)
  assert.match(noticeSource, /command="\/antv-g6-examples"/)
  assert.match(noticeSource, /command="\/antv-f2-examples"/)
  assert.match(noticeSource, /command="\/antv-l7-examples"/)
  assert.match(noticeSource, /command="\/source-code"/)
  assert.match(noticeSource, /command="\/docker-showcase"/)
  assert.match(cartSource, /generate100Carts/)
  assert.match(animSource, /generate63kAnims/)
})

test('mapcn showcase calls article-mentioned MapLibre UI components from the dropdown route', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const mapcnSource = readFileSync(new URL('../src/views/mapcnShowcase/index.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /views\/mapcnShowcase\/index\.vue/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?\/mapcn-showcase/)
  assert.match(noticeSource, /mapcn MapLibre 地图 UI 组件库/)
  assert.match(mapcnSource, /ZoomControl/)
  assert.match(mapcnSource, /CompassControl/)
  assert.match(mapcnSource, /LayerSwitcher/)
  assert.match(mapcnSource, /Marker \+ Popup/)
  assert.match(mapcnSource, /ThemeToggle/)
})

test('AntV official examples are split into S2 G6 F2 and L7 route pages from basic to expert', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const sharedSource = readFileSync(new URL('../src/components/antv/AntvExamplesPage.vue', import.meta.url), 'utf8')
  const s2Source = readFileSync(new URL('../src/views/antvS2Examples/index.vue', import.meta.url), 'utf8')
  const g6Source = readFileSync(new URL('../src/views/antvG6Examples/index.vue', import.meta.url), 'utf8')
  const f2Source = readFileSync(new URL('../src/views/antvF2Examples/index.vue', import.meta.url), 'utf8')
  const l7Source = readFileSync(new URL('../src/views/antvL7Examples/index.vue', import.meta.url), 'utf8')

  for (const routePath of ['/antv-s2-examples', '/antv-g6-examples', '/antv-f2-examples', '/antv-l7-examples']) {
    assert.match(routerSource, new RegExp(`path:\\s*'${routePath}'`))
    assert.match(appSource, new RegExp(`routeViewPaths:[\\s\\S]*?${routePath}`))
    assert.match(noticeSource, new RegExp(`command="${routePath}"`))
  }

  assert.match(routerSource, /views\/antvS2Examples\/index\.vue/)
  assert.match(routerSource, /views\/antvG6Examples\/index\.vue/)
  assert.match(routerSource, /views\/antvF2Examples\/index\.vue/)
  assert.match(routerSource, /views\/antvL7Examples\/index\.vue/)
  assert.match(sharedSource, /basic/)
  assert.match(sharedSource, /advanced/)
  assert.match(sharedSource, /expert/)
  assert.match(s2Source, /https:\/\/s2\.antv\.antgroup\.com\/examples/)
  assert.match(g6Source, /https:\/\/g6\.antv\.antgroup\.com\/examples/)
  assert.match(f2Source, /https:\/\/f2\.antv\.antgroup\.com\/examples/)
  assert.match(l7Source, /https:\/\/l7\.antv\.antgroup\.com\/examples/)
  assert.match(s2Source, /透视表/)
  assert.match(g6Source, /Force Atlas 2/)
  assert.match(f2Source, /Apple Watch 健身记录/)
  assert.match(l7Source, /风场图层/)
})

test('Centralized storage keys constants and universal LocalStorage utility are provided', () => {
  const storageKeysSource = readFileSync(new URL('../src/constants/storageKeys.ts', import.meta.url), 'utf8')
  const storageUtilSource = readFileSync(new URL('../src/utils/storage.ts', import.meta.url), 'utf8')
  const scheduleSource = readFileSync(new URL('../src/views/scheduleXShowcase/index.vue', import.meta.url), 'utf8')

  assert.match(storageKeysSource, /SCHEDULE_X_EVENTS/)
  assert.match(storageKeysSource, /SCHEDULE_X_CATEGORIES/)
  assert.match(storageUtilSource, /class LocalStorageUtil/)
  assert.match(scheduleSource, /storage\.getItem/)
  assert.match(scheduleSource, /STORAGE_KEYS\.SCHEDULE_X_EVENTS/)
})

test('Version polling is configured for production app initialization with Element Plus UI dialog', () => {
  const versionPollingSource = readFileSync(new URL('../src/utils/versionPolling.ts', import.meta.url), 'utf8')
  const mainSource = readFileSync(new URL('../src/kglobal/main.ts', import.meta.url), 'utf8')

  assert.match(mainSource, /initVersionPolling\(\)/)
  assert.match(mainSource, /initDevToolsProtection\(\)/)
  assert.match(versionPollingSource, /createVersionPolling/)
  assert.match(versionPollingSource, /import\.meta\.env\.PROD/)
  assert.match(versionPollingSource, /vcType:\s*'versionJson'/)
  assert.match(versionPollingSource, /ElMessageBox\.confirm/)
})

test('RunCode page includes editor input output and run controls', () => {
  const runCodeSource = readFileSync(new URL('../src/views/runcode/index.vue', import.meta.url), 'utf8')

  assert.match(runCodeSource, /class="runcode-workbench"/)
  assert.match(runCodeSource, /v-model="selectedLanguageId"/)
  assert.match(runCodeSource, /v-model="sourceCode"/)
  assert.match(runCodeSource, /v-model="stdinText"/)
  assert.match(runCodeSource, /runCode/)
  assert.match(runCodeSource, /outputText/)
})

test('DyForm opens a future info Element Plus dialog with links runtime versions and huge token records', () => {
  const dyFormSource = readFileSync(new URL('../src/views/DyForm.vue', import.meta.url), 'utf8')
  const dyFormStyleSource = readFileSync(new URL('../src/views/css/DyForm.scss', import.meta.url), 'utf8')

  assert.match(dyFormSource, /<el-dialog[\s\S]*?class="dy-form-future-dialog"[\s\S]*?append-to-body[\s\S]*?align-center/)
  assert.match(dyFormSource, /isFutureDialogVisible\.value = true/)
  assert.match(dyFormSource, /https:\/\/element-plus\.org\/zh-CN\/component\/dialog/)
  assert.match(dyFormSource, /https:\/\/ai-bot\.cn\//)
  assert.match(dyFormSource, /https:\/\/github\.com\/mhxy13867806343/)
  assert.match(dyFormSource, /https:\/\/gitee\.com\/fangjiayu/)
  assert.match(dyFormSource, /https:\/\/steamcommunity\.com\/profiles\/76561198384042673\//)
  assert.match(dyFormSource, /Codex/)
  assert.match(dyFormSource, /Antigravity/)
  assert.match(dyFormSource, /Trae/)
  assert.match(dyFormSource, /WorkBuddy/)
  assert.match(dyFormSource, /512\.8亿/)
  assert.match(dyFormSource, /3000亿\+/)
  assert.match(dyFormSource, /macOS 26\.5/)
  assert.match(dyFormSource, /Python 3\.11\.9/)
  assert.match(dyFormSource, /4\.6\.stable\.official/)
  assert.match(dyFormSource, /rustc 1\.91\.0/)
  assert.match(dyFormSource, /currentYear/)
  assert.match(dyFormSource, /nextYear/)
  assert.match(dyFormSource, /未来可期/)
  assert.match(dyFormSource, /嘿嘿嘿/)
  assert.match(dyFormSource, /没有了，再见/)
  assert.match(dyFormStyleSource, /\.token-wall/)
  assert.match(dyFormStyleSource, /\.dy-form-info-toggle/)
})

test('Home page keeps quick-entry clock without floating QQ and email contact buttons', () => {
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const clockSource = readFileSync(new URL('../src/components/AnalogClock.vue', import.meta.url), 'utf8')
  const styleSource = readFileSync(new URL('../src/style/style.scss', import.meta.url), 'utf8')

  assert.match(appSource, /mqqwpa:\/\/im\/chat\?chat_type=wpa&uin=869710179&version=1&src_type=web/)
  assert.match(appSource, /import AnalogClock from '\.\/components\/AnalogClock\.vue'/)
  assert.match(appSource, /<AnalogClock class="header-analog-clock" \/>/)
  assert.match(clockSource, /<el-dialog[\s\S]*?append-to-body[\s\S]*?align-center/)
  assert.match(clockSource, /<el-dialog[\s\S]*?draggable/)
  assert.match(clockSource, /@contextmenu\.prevent="openClockContextMenu"/)
  assert.match(clockSource, /class="clock-context-menu"/)
  assert.match(clockSource, /隐藏弹窗/)
  assert.match(clockSource, /hideClockDialogFromMenu/)
  assert.match(clockSource, /time-greeting/)
  assert.match(clockSource, /凌晨/)
  assert.match(clockSource, /早上/)
  assert.match(clockSource, /中午/)
  assert.match(clockSource, /下午/)
  assert.match(clockSource, /晚上[\s\S]*?睡觉/)
  assert.match(appSource, /<el-dropdown trigger="click" placement="bottom" :teleported="true"/)
  assert.match(styleSource, /\.header-analog-clock\s*\{[\s\S]*?--clock-size:\s*28px/)
  assert.match(styleSource, /\.header-right-actions\s*\{[\s\S]*?width:\s*196px[\s\S]*?height:\s*52px[\s\S]*?overflow:\s*visible/)
  assert.match(styleSource, /\.header-right-actions \.el-dropdown\s*\{[\s\S]*?flex:\s*0 0 132px/)
  assert.match(styleSource, /\.quick-actions-trigger\s*\{[\s\S]*?width:\s*132px/)
  const headerActionsBlocks = [...styleSource.matchAll(/\.header-right-actions\s*\{([^}]*)\}/g)].map((match) => match[1])
  assert.ok(headerActionsBlocks.length > 0)
  assert.ok(headerActionsBlocks.every((block) => !/flex-wrap:\s*wrap\b/.test(block)))
  assert.doesNotMatch(appSource, /class="floating-contact-bar"/)
  assert.doesNotMatch(appSource, /class="floating-contact-icon floating-qq-icon"/)
  assert.doesNotMatch(appSource, /class="floating-contact-icon floating-email-icon"/)
  assert.doesNotMatch(styleSource, /\.floating-contact-bar\s*\{/)
  assert.doesNotMatch(styleSource, /\.floating-contact-icon\s*\{/)
})

test('Juejin theme avatar opens detail modal before external navigation', () => {
  const pageSource = readFileSync(new URL('../src/views/juejinTheme/index.vue', import.meta.url), 'utf8')
  const mapperSource = readFileSync(new URL('../src/vue-pages-text-fn-abc/juejinTheme.ts', import.meta.url), 'utf8')

  assert.match(pageSource, /@click\.prevent\.stop="handleAvatarClick\(u\)"/)
  assert.match(pageSource, /function handleAvatarClick\(u: ThemeRecentUser\): void \{\s*showUserDetailModal\(u\)\s*\}/)
  assert.match(pageSource, /selectedUserFields/)
  assert.match(pageSource, /全部资料/)
  assert.doesNotMatch(mapperSource, /recentUsers:\s*\(raw\.recent_users\s*\|\|\s*\)\.slice/)
})

test('Juejin course page loads booklet list and keeps course-list links', () => {
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const noticeStyleSource = readFileSync(new URL('../src/components/css/BrowserSupportNotice.scss', import.meta.url), 'utf8')
  const pageSource = readFileSync(new URL('../src/views/juejinCourse/index.vue', import.meta.url), 'utf8')
  const juejinConstantsSource = readFileSync(new URL('../src/constants/juejin.ts', import.meta.url), 'utf8')
  const liveDataConstantsSource = readFileSync(new URL('../src/constants/liveData.ts', import.meta.url), 'utf8')
  const packageSource = readFileSync(new URL('../package.json', import.meta.url), 'utf8')
  const cacheScriptSource = readFileSync(new URL('../scripts/generate-juejin-course-cache.mts', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/juejin-course'[\s\S]*?name:\s*'JuejinCourse'/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/juejin-course'/)
  assert.match(noticeSource, /<el-dropdown-item divided disabled>🆕 新建页面<\/el-dropdown-item>/)
  assert.match(noticeSource, /command="\/juejin-course">📘 掘金小册课程/)
  assert.doesNotMatch(appSource, /goJuejinCourse/)
  assert.match(noticeStyleSource, /\.web-library-items\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(juejinConstantsSource, /JUEJIN_COURSE_API = '\/api-juejin\/booklet_api\/v1\/booklet\/listbycategory'/)
  assert.match(juejinConstantsSource, /JUEJIN_COURSE_CATEGORY_API = '\/api-juejin\/tag_api\/v1\/query_category_briefs\?show_type=1'/)
  assert.match(pageSource, /category_id:\s*selectedCategoryId\.value[\s\S]*?cursor:\s*append \? cursor\.value : '0'[\s\S]*?sort:\s*sortValue\.value[\s\S]*?is_vip:\s*vipOnly\.value \? 1 : 0[\s\S]*?limit:\s*20/)
  assert.match(juejinConstantsSource, /JUEJIN_COURSE_FALLBACK_CATEGORIES[\s\S]*?category_name:\s*'后端'[\s\S]*?category_name:\s*'前端'[\s\S]*?category_name:\s*'Android'[\s\S]*?category_name:\s*'iOS'[\s\S]*?category_name:\s*'人工智能'[\s\S]*?category_name:\s*'开发工具'[\s\S]*?category_name:\s*'代码人生'[\s\S]*?category_name:\s*'阅读'/)
  assert.match(juejinConstantsSource, /JUEJIN_COURSE_SORT_PRICE_ASC = 8[\s\S]*?JUEJIN_COURSE_SORT_PRICE_DESC = 9/)
  assert.match(pageSource, /function togglePriceSort\(\): void \{[\s\S]*?JUEJIN_COURSE_SORT_PRICE_DESC \? JUEJIN_COURSE_SORT_PRICE_ASC : JUEJIN_COURSE_SORT_PRICE_DESC/)
  assert.match(pageSource, /can_vip_borrow\?: boolean/)
  assert.match(pageSource, /function isVipBook\(course: JuejinCourseItem\): boolean \{[\s\S]*?course\.base_info\.can_vip_borrow/)
  assert.match(pageSource, /function displayPrice\(course: JuejinCourseItem\): number \{[\s\S]*?eventDiscountPrice\(course\) \?\? course\.max_discount\?\.pay_money \?\? course\.base_info\.price/)
  assert.match(pageSource, /function eventDiscountPrice\(course: JuejinCourseItem\): number \| null \{[\s\S]*?Math\.round\(course\.base_info\.price \* rate \/ 10\)/)
  assert.match(pageSource, /function eventDiscountLabel\(course: JuejinCourseItem\): string \{[\s\S]*?'限时优惠价'/)
  assert.match(pageSource, /function syncServerClock\(response: Response\): void \{[\s\S]*?x-tt-timestamp[\s\S]*?serverClockOffsetMs/)
  assert.match(liveDataConstantsSource, /JUEJIN_COURSE_CACHE_FILE = 'juejin-course-cache\.json'/)
  assert.match(pageSource, /courseCacheUrl = buildLiveDataUrl\(JUEJIN_COURSE_CACHE_FILE\)/)
  assert.match(pageSource, /if \(isProd\) \{[\s\S]*?fetchCachedCourses\(\)[\s\S]*?hasMore\.value = false/)
  assert.match(pageSource, /function courseCacheKey\(categoryId: string, sort: number, isVip: number\): string \{[\s\S]*?`\$\{categoryId\}:\$\{sort\}:\$\{isVip\}`/)
  assert.match(packageSource, /generate-juejin-rank-cache\.mts && node scripts\/generate-juejin-course-cache\.mts/)
  assert.match(cacheScriptSource, /publicCachePath[\s\S]*?public[\s\S]*?LIVE_DATA_DIR[\s\S]*?JUEJIN_COURSE_CACHE_FILE/)
  assert.match(cacheScriptSource, /courseCacheKey\(categoryId: string, sort: number, isVip: number\)/)
  assert.match(pageSource, /@click\.stop="openUser\(course\.user_info\.user_id\)"/)
  assert.match(juejinConstantsSource, /buildJuejinUserUrl\(userId: string\)/)
  assert.match(juejinConstantsSource, /buildJuejinBookUrl\(bookletId: string\)/)
})

test('AI tutorial resources use internal ai-xxx routes instead of external ai-bot links', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const aiXxxSource = readFileSync(new URL('../src/views/ai-xxx/index.vue', import.meta.url), 'utf8')
  const articlesSource = readFileSync(new URL('../src/components/AiArticlesList.vue', import.meta.url), 'utf8')

  for (const section of ['ai-research', 'ai-column', 'ai-question-and-answer', 'ai-encyclopedia', 'ai-hall-of-fame']) {
    assert.match(routerSource, /path:\s*'\/ai-xxx\/:section'/)
    assert.match(appSource, new RegExp(`to="\\/ai-xxx\\/${section}"`))
    assert.match(aiXxxSource, new RegExp(`/ai-xxx/${section}`))
  }

  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/ai-xxx'/)
  assert.doesNotMatch(appSource, /href="https:\/\/ai-bot\.cn\/ai-column\/"/)
  assert.doesNotMatch(appSource, /href="https:\/\/ai-bot\.cn\/ai-question-and-answer\/"/)
  assert.doesNotMatch(appSource, /href="https:\/\/ai-bot\.cn\/ai-encyclopedia\/"/)
  assert.doesNotMatch(appSource, /href="https:\/\/ai-bot\.cn\/ai-hall-of-fame\/"/)
  assert.match(articlesSource, /type ArticleType = 'tutorials' \| 'column'/)
  assert.match(articlesSource, /proxyPath:\s*'\/api-column'/)
  assert.match(articlesSource, /proxyPath:\s*'\/api-research'/)
  assert.match(aiXxxSource, /isArticlesLoading/)
  assert.match(aiXxxSource, /@click="handleTabClick"/)
  assert.match(aiXxxSource, /@loading-change="isArticlesLoading = \$event"/)
  assert.match(articlesSource, /emit\('loading-change', true\)/)
  assert.match(articlesSource, /articlesList\.value = \[\]/)
  assert.match(articlesSource, /:disabled="isLoading"/)
})

test('Jandan and TopHub pages are internal routes with visible parsed feed data', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const jandanSource = readFileSync(new URL('../src/views/jandan/index.vue', import.meta.url), 'utf8')
  const tophubSource = readFileSync(new URL('../src/views/tophub/index.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/jandan'[\s\S]*?name:\s*'Jandan'/)
  assert.match(routerSource, /path:\s*'\/tophub'[\s\S]*?name:\s*'TopHub'/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/jandan'[\s\S]*?'\/tophub'/)
  assert.match(noticeSource, /command:\s*'\/jandan'/)
  assert.match(noticeSource, /command:\s*'\/tophub'/)
  assert.match(noticeSource, /command="\/jandan">🥚 煎蛋页面/)
  assert.match(noticeSource, /command="\/tophub">🔥 今日热榜 TopHub/)

  for (const sourcePath of ['treehole', 'beauty', 'ooxx', 'pic', 'new/forum', 'top#tab=4hr', 'tucao']) {
    assert.match(jandanSource, new RegExp(`https://jandan\\.net/${sourcePath.replace('/', '\\/')}`))
  }

  assert.match(jandanSource, /parseHomeHtml/)
  assert.match(jandanSource, /parseHomePagination/)
  assert.match(jandanSource, /mapForumItems/)
  assert.match(jandanSource, /mapCommentListItems/)
  assert.match(jandanSource, /\/api-jandan\/api\/top\/4hr/)
  assert.match(jandanSource, /\/api-jandan\/api\/top\/tucao/)
  assert.match(jandanSource, /buildProxyPath/)
  assert.match(jandanSource, /buildSourceUrl/)
  assert.match(jandanSource, /\/api-jandan\/page\/\$\{page\}/)
  assert.match(jandanSource, /\/api-jandan\/api\/comment\/post\/\$\{section\.pageId\}\?order=desc&page=\$\{requestPage\}/)
  assert.match(jandanSource, /total_pages/)
  assert.match(jandanSource, /current_page/)
  assert.match(jandanSource, /page-controls/)
  assert.match(jandanSource, /class="\{ 'has-image': item\.image \}"/)
  assert.match(jandanSource, /requestTextWithFallback/)
  assert.match(jandanSource, /if \(isLoading\.value \|\| activeSectionId\.value === sectionId\) return/)
  assert.match(jandanSource, /:disabled="isLoading"/)
  assert.match(tophubSource, /parseTopHubHtml/)
  assert.match(tophubSource, /parseTopHubMarkdown/)
  assert.match(tophubSource, /parsePaginationHtml/)
  assert.match(tophubSource, /parsePaginationMarkdown/)
  assert.match(tophubSource, /parseCalendarMarkdown/)
  assert.match(tophubSource, /requestTextWithTimeout/)
  assert.match(tophubSource, /boardIconLabel/)
  assert.match(tophubSource, /section-tabs/)
  assert.match(tophubSource, /subsection-tabs/)
  assert.match(tophubSource, /board-grid/)
  assert.match(tophubSource, /board-card/)
  assert.match(tophubSource, /board-card-item/)
  assert.match(tophubSource, /page-controls/)
  assert.match(tophubSource, /class="board-icon"/)
  for (const sourcePath of ['/calendar', '/c/news', '/c/tech', '/c/ent', '/c/community', '/c/shopping', '/c/finance', '/c/developer', '/c/brief', '/c/ai']) {
    assert.match(tophubSource, new RegExp(`path:\\s*'${sourcePath}'`))
  }
  for (const sourcePath of ['/c/epaper', '/c/design', '/c/university', '/c/organization', '/c/blog', '/apple', '/c/wxmp', '/c/widget', '/manage']) {
    assert.match(tophubSource, new RegExp(`path:\\s*'${sourcePath}'`))
  }
  assert.match(tophubSource, /page > 1 \? `\?&p=\$\{page\}` : ''/)
  assert.match(tophubSource, /https:\/\/r\.jina\.ai\/http:\/\/\$\{sourceUrl\}/)
  assert.doesNotMatch(tophubSource, /r\.jina\.ai\/http:\/\/r\.jina\.ai\/http/)
  assert.match(tophubSource, /\.cc-cd, \.cc-bo, \.cc-mp/)
  assert.match(tophubSource, /批量订阅本页全部节点/)
  assert.match(tophubSource, /ArrowLeft/)
  assert.match(tophubSource, /ArrowRight/)
  assert.match(tophubSource, /cc-cd/)
  assert.match(tophubSource, /requestTopHubText/)
  assert.match(tophubSource, /if \(isLoading\.value \|\| activeSectionId\.value === sectionId\) return/)
  assert.match(tophubSource, /:disabled="isLoading"/)
})

test('Ithome Huxiu and Github collection pages are internal parsed feeds', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const ithomeSource = readFileSync(new URL('../src/views/ithome/index.vue', import.meta.url), 'utf8')
  const huxiuSource = readFileSync(new URL('../src/views/huxiu/index.vue', import.meta.url), 'utf8')
  const githubSource = readFileSync(new URL('../src/views/github/index.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/ithome'[\s\S]*?name:\s*'Ithome'/)
  assert.match(routerSource, /path:\s*'\/huxiu'[\s\S]*?name:\s*'Huxiu'/)
  assert.match(routerSource, /path:\s*'\/github'[\s\S]*?name:\s*'Github'/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/ithome'[\s\S]*?'\/huxiu'[\s\S]*?'\/github'/)
  assert.match(noticeSource, /command:\s*'\/ithome'/)
  assert.match(noticeSource, /command:\s*'\/huxiu'/)
  assert.match(noticeSource, /command:\s*'\/github'/)
  assert.match(noticeSource, /command="\/ithome">📰 IT之家/)
  assert.match(noticeSource, /command="\/huxiu">🐯 虎嗅24小时/)
  assert.match(noticeSource, /command="\/github">🐙 GitHub开源聚合/)

  assert.match(ithomeSource, /path:\s*'\/hudong'/)
  assert.match(ithomeSource, /https:\/\/it\.ithome\.com\$\{path\}/)
  assert.match(ithomeSource, /\/api-ithome-web\$\{path\}/)
  assert.match(ithomeSource, /parseItems/)
  assert.match(ithomeSource, /parseRanks/)
  assert.match(ithomeSource, /section-tabs/)
  assert.match(ithomeSource, /pageSize = 8/)
  assert.match(ithomeSource, /visibleItems/)
  assert.match(ithomeSource, /errorMessage && !items\.length/)
  assert.match(ithomeSource, /page-controls/)
  assert.match(ithomeSource, /shouldShowContent/)
  assert.match(ithomeSource, /items\.value = \[\]/)
  assert.match(ithomeSource, /class="loading-panel"/)
  assert.match(ithomeSource, /:disabled="isLoading"/)

  assert.match(huxiuSource, /https:\/\/www\.huxiu\.com\/moment\//)
  assert.match(huxiuSource, /https:\/\/r\.jina\.ai\/http:\/\/\$\{buildSourceUrl\(tab\)\}/)
  assert.match(huxiuSource, /parseMoments/)
  assert.match(huxiuSource, /moment-tabs/)
  assert.match(huxiuSource, /currentPage/)
  assert.match(huxiuSource, /params\.set\('page'/)
  assert.match(huxiuSource, /function goPage/)
  assert.match(huxiuSource, /page-controls/)
  assert.match(huxiuSource, /pageButtons/)
  assert.match(huxiuSource, /gap-\$\{previous\}-\$\{page\}/)
  assert.match(huxiuSource, /typeof page === 'number' \? page : '\.\.\.'/)
  assert.match(huxiuSource, /shouldShowContent/)
  assert.match(huxiuSource, /items\.value = \[\]/)
  assert.match(huxiuSource, /class="loading-panel"/)
  assert.match(huxiuSource, /:disabled="isLoading"/)

  assert.match(githubSource, /https:\/\/gitcn\.org\/trending/)
  assert.match(githubSource, /https:\/\/gitcn\.org\/trends\/monthly/)
  assert.match(githubSource, /https:\/\/githot\.dev\/archive/)
  assert.match(githubSource, /https:\/\/hellogithub\.com\/periodical/)
  assert.match(githubSource, /\/api-gitcn\/trending/)
  assert.match(githubSource, /\/api-gitcn\/trends\/monthly/)
  assert.match(githubSource, /\/api-githot\/archive/)
  assert.match(githubSource, /parseGitcnProjects/)
  assert.match(githubSource, /parseArchive/)
  assert.match(githubSource, /parseHelloGithub/)
  assert.match(githubSource, /helloCategories/)
  assert.match(githubSource, /helloIssues/)
  assert.match(githubSource, /displayedHelloIssues/)
  assert.match(githubSource, /showOlderHelloIssues/)
  assert.match(githubSource, /更早/)
  assert.match(githubSource, /type HelloGithubMode/)
  assert.match(githubSource, /activeHelloMode/)
  assert.match(githubSource, /buildHelloGithubSourceUrl/)
  assert.match(githubSource, /function selectHelloIssue/)
  assert.match(githubSource, /function selectHelloCategory/)
  assert.match(githubSource, /toHelloGithubImageUrl/)
  assert.match(githubSource, /\/api-hellogithub-img/)
  assert.match(githubSource, /helloImageErrors/)
  assert.match(githubSource, /class="content-state"/)
  assert.match(githubSource, /:disabled="isLoading"/)
  assert.match(githubSource, /referrerpolicy="no-referrer"/)
  assert.match(githubSource, /hello-image-fallback/)
  assert.match(githubSource, /archive-grid/)
})

test('records cache page renders cloud tags two-column cards and favorite controls', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const appStyleSource = readFileSync(new URL('../src/App.scss', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const storageKeysSource = readFileSync(new URL('../src/constants/storageKeys.ts', import.meta.url), 'utf8')
  const pageSource = readFileSync(new URL('../src/views/recordsCache/index.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/records-cache'[\s\S]*?name:\s*'RecordsCache'/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/records-cache'/)
  assert.match(appSource, /case 'records-cache':/)
  assert.match(appSource, /goRecordsCache/)
  assert.match(appSource, /route-page-favorite/)
  assert.match(appSource, /isRouteFavoriteVisible/)
  assert.match(appSource, /!\['\/records-cache',\s*'\/share-records'\]\.includes\(route\.path\)/)
  assert.match(appSource, /route-page-share/)
  assert.match(appSource, /currentRouteSharePayload/)
  assert.match(appSource, /toolSharePayload/)
  assert.match(appSource, /class="tool-card-share"/)
  assert.match(appSource, /STORAGE_KEYS\.PAGE_FAVORITES/)
  assert.match(appStyleSource, /\.route-page-favorite/)
  assert.match(appStyleSource, /\.route-page-share/)
  assert.match(noticeSource, /command:\s*'\/records-cache'/)
  assert.match(noticeSource, /command="\/records-cache">♡ 记录缓存展示/)
  assert.match(noticeSource, /command:\s*'\/share-records'/)
  assert.match(noticeSource, /command="\/share-records">↗ 分享记录展示/)
  assert.match(storageKeysSource, /PAGE_FAVORITES: 'HOOKSVUE_PAGE_FAVORITES_V1'/)
  assert.match(storageKeysSource, /RECORD_CACHE_FAVORITES: 'HOOKSVUE_RECORD_CACHE_FAVORITES_V1'/)
  assert.match(storageKeysSource, /CONTENT_ITEM_FAVORITES: 'HOOKSVUE_CONTENT_ITEM_FAVORITES_V1'/)
  assert.match(storageKeysSource, /SHARE_RECORDS: 'HOOKSVUE_SHARE_RECORDS_V1'/)

  assert.match(pageSource, /class="cloud-panel"/)
  assert.match(pageSource, /class="records-grid"/)
  assert.match(pageSource, /grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(pageSource, /record-heart/)
  assert.match(pageSource, /ShareButton/)
  assert.match(pageSource, /recordSharePayload/)
  assert.match(pageSource, /ElMessageBox\.confirm/)
  assert.match(pageSource, /confirmFavoriteRemoval/)
  assert.match(pageSource, /togglePageFavorite/)
  assert.match(pageSource, /toggleRecordFavorite/)
  assert.match(pageSource, /toggleContentFavorite/)
  assert.match(pageSource, /toggleEntryFavorite/)
  assert.match(pageSource, /isEntryFavorite\(entry\)/)
  assert.match(pageSource, /contentFavoriteId:\s*id/)
  assert.match(pageSource, /CONTENT_ITEM_FAVORITES/)
  assert.match(pageSource, /contentFavoriteEntries/)
  assert.match(pageSource, /recordFavoriteEntries/)
  assert.match(pageSource, /\.\.\.pageFavoriteEntries\.value,[\s\S]*?\.\.\.contentFavoriteEntries\.value,[\s\S]*?\.\.\.recordFavoriteEntries\.value/)
  assert.match(pageSource, /暂无收藏记录/)
  assert.match(pageSource, /buildLiveDataUrl\(JUEJIN_COURSE_CACHE_FILE\)/)
  assert.match(pageSource, /window\.localStorage\.length/)
  assert.match(pageSource, /中转进入/)
  assert.match(pageSource, /isRefreshing/)
  assert.match(pageSource, /正在加载记录缓存/)
  assert.match(pageSource, /:disabled="isRefreshing"/)
  assert.match(pageSource, /:title="`\$\{tag\.title\} \(\$\{tag\.count\} 条\)`"/)
  assert.match(pageSource, /max-width:\s*3em/)
  assert.match(pageSource, /@include text-ellipsis/)
  assert.match(pageSource, /@include line-clamp\(2\)/)
})

test('Juejin theme cards provide item-level favorite controls saved into content favorites', () => {
  const storageKeysSource = readFileSync(new URL('../src/constants/storageKeys.ts', import.meta.url), 'utf8')
  const pageSource = readFileSync(new URL('../src/views/juejinTheme/index.vue', import.meta.url), 'utf8')
  const styleSource = readFileSync(new URL('../src/views/juejinTheme/css/index.scss', import.meta.url), 'utf8')

  assert.match(storageKeysSource, /CONTENT_ITEM_FAVORITES: 'HOOKSVUE_CONTENT_ITEM_FAVORITES_V1'/)
  assert.match(pageSource, /STORAGE_KEYS\.CONTENT_ITEM_FAVORITES/)
  assert.match(pageSource, /theme-card-favorite/)
  assert.match(pageSource, /ShareButton/)
  assert.match(pageSource, /themeSharePayload/)
  assert.match(pageSource, /ElMessageBox\.confirm/)
  assert.match(pageSource, /toggleThemeFavorite\(item\)/)
  assert.match(pageSource, /isThemeFavorite\(item\)/)
  assert.match(pageSource, /juejin-theme:\$\{item\.id\}/)
  assert.match(pageSource, /hooksvue-content-favorites-change/)
  assert.match(pageSource, /source: '掘金热门主题'/)
  assert.match(styleSource, /\.theme-card-favorite/)
  assert.match(styleSource, /\.theme-card\.favorited/)
  assert.match(styleSource, /\.theme-card-share/)
  assert.match(styleSource, /@include line-clamp\(2\)/)
  assert.match(styleSource, /right:\s*24px/)
})

test('new internal list pages share item-level content favorite buttons', () => {
  const composableSource = readFileSync(new URL('../src/composables/useContentItemFavorites.ts', import.meta.url), 'utf8')
  const buttonSource = readFileSync(new URL('../src/components/ContentFavoriteButton.vue', import.meta.url), 'utf8')
  const listPages = [
    '../src/components/AiArticlesList.vue',
    '../src/components/AiAppStore.vue',
    '../src/components/AiNewsTimeline.vue',
    '../src/views/aicoding/index.vue',
    '../src/views/tophub/index.vue',
    '../src/views/ithome/index.vue',
    '../src/views/huxiu/index.vue',
    '../src/views/github/index.vue',
    '../src/views/helloworld/index.vue',
    '../src/views/jandan/index.vue'
  ]

  assert.match(composableSource, /CONTENT_FAVORITES_CHANGE_EVENT/)
  assert.match(composableSource, /STORAGE_KEYS\.CONTENT_ITEM_FAVORITES/)
  assert.match(composableSource, /ElMessageBox\.confirm/)
  assert.match(composableSource, /toggleContentItemFavorite/)
  assert.match(buttonSource, /content-favorite-button/)
  assert.match(buttonSource, /@click\.stop\.prevent/)

  for (const filePath of listPages) {
    const source = readFileSync(new URL(filePath, import.meta.url), 'utf8')
    assert.match(source, /ContentFavoriteButton/)
    assert.match(source, /useContentItemFavorites/)
    assert.match(source, /toggleContentItemFavorite/)
    assert.match(source, /ShareButton/)
    assert.match(source, /SharePayload/)
  }

  assert.match(readFileSync(new URL('../src/views/tophub/index.vue', import.meta.url), 'utf8'), /board-item-favorite/)
  assert.match(readFileSync(new URL('../src/views/tophub/index.vue', import.meta.url), 'utf8'), /tophubItemSharePayload/)
  assert.match(readFileSync(new URL('../src/views/jandan/index.vue', import.meta.url), 'utf8'), /feed-card-favorite/)
  assert.match(readFileSync(new URL('../src/views/jandan/index.vue', import.meta.url), 'utf8'), /jandanSharePayload/)
  assert.match(readFileSync(new URL('../src/views/helloworld/index.vue', import.meta.url), 'utf8'), /hello-list-favorite/)
  assert.match(readFileSync(new URL('../src/views/helloworld/index.vue', import.meta.url), 'utf8'), /helloArticleSharePayload/)
})

test('share records page and shared share button use social share hooks', () => {
  const packageSource = readFileSync(new URL('../package.json', import.meta.url), 'utf8')
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const storageKeysSource = readFileSync(new URL('../src/constants/storageKeys.ts', import.meta.url), 'utf8')
  const composableSource = readFileSync(new URL('../src/composables/useShareRecords.ts', import.meta.url), 'utf8')
  const buttonSource = readFileSync(new URL('../src/components/ShareButton.vue', import.meta.url), 'utf8')
  const pageSource = readFileSync(new URL('../src/views/shareRecords/index.vue', import.meta.url), 'utf8')

  assert.match(packageSource, /"social-share\.js":/)
  assert.match(routerSource, /path:\s*'\/share-records'[\s\S]*?name:\s*'ShareRecords'/)
  assert.match(appSource, /case 'share-records':/)
  assert.match(appSource, /route-page-share/)
  assert.match(appSource, /!\['\/records-cache',\s*'\/share-records'\]\.includes\(route\.path\)/)
  assert.match(appSource, /toolSharePayload/)
  assert.match(appSource, /class="tool-card-share"/)
  assert.match(storageKeysSource, /SHARE_RECORDS: 'HOOKSVUE_SHARE_RECORDS_V1'/)
  assert.match(composableSource, /SHARE_RECORDS_CHANGE_EVENT/)
  assert.match(composableSource, /buildShareUrl/)
  assert.match(composableSource, /recordShare/)
  assert.match(composableSource, /copyShareLink/)
  assert.match(composableSource, /writeClipboardText/)
  assert.match(buttonSource, /social-share\.js\/dist\/css\/share\.min\.css/)
  assert.doesNotMatch(buttonSource, /social-share\.js\/dist\/js\/social-share\.min\.js/)
  assert.doesNotMatch(buttonSource, /window\.socialShare/)
  assert.match(buttonSource, /shareLinks/)
  assert.match(buttonSource, /openShareLink/)
  assert.match(buttonSource, /<Teleport to="body">/)
  assert.match(buttonSource, /updatePopoverPosition/)
  assert.match(buttonSource, /position:\s*'fixed'/)
  assert.match(buttonSource, /service\.weibo\.com\/share/)
  assert.match(buttonSource, /connect\.qq\.com\/widget\/shareqq/)
  assert.match(buttonSource, /sns\.qzone\.qq\.com/)
  assert.match(buttonSource, /douban/)
  assert.match(buttonSource, /recordShare\(props\.payload\)/)
  assert.match(pageSource, /class="share-records-page"/)
  assert.match(pageSource, /class="cloud-panel"/)
  assert.match(pageSource, /class="records-grid"/)
  assert.match(pageSource, /max-width:\s*3em/)
  assert.match(pageSource, /@include text-ellipsis/)
  assert.match(pageSource, /@include line-clamp\(2\)/)
  assert.doesNotMatch(pageSource, /record-heart/)
})

test('line clamp styles are centralized through the shared SCSS mixin', () => {
  const mixinsSource = readFileSync(new URL('../src/style/mixins.scss', import.meta.url), 'utf8')
  const files = [
    '../src/style/style.scss',
    '../src/components/css/ApiToolbox.scss',
    '../src/components/css/AiArticlesList.scss',
    '../src/components/css/AiAppStore.scss',
    '../src/components/css/AiNewsTimeline.scss',
    '../src/views/aicoding/css/index.scss',
    '../src/views/bilibiliTrending/css/index.scss',
    '../src/views/cnblogs/css/index.scss',
    '../src/views/cocoloop/css/index.scss',
    '../src/views/githubCn/css/index.scss',
    '../src/views/helloworld/css/index.scss',
    '../src/views/jandan/index.vue',
    '../src/views/juejinCourse/index.vue',
    '../src/views/juejinTheme/css/index.scss',
    '../src/views/mingyan/index.vue',
    '../src/views/mingyan/css/index.scss',
    '../src/views/recordsCache/index.vue',
    '../src/views/shareRecords/index.vue'
  ]

  assert.match(mixinsSource, /@mixin line-clamp\(\$lines:\s*2\)/)
  assert.match(mixinsSource, /@mixin text-ellipsis/)

  for (const filePath of files) {
    const source = readFileSync(new URL(filePath, import.meta.url), 'utf8')
    assert.doesNotMatch(source, /display:\s*-webkit-box/)
    assert.doesNotMatch(source, /-webkit-line-clamp:\s*\d/)
    assert.doesNotMatch(source, /-webkit-box-orient:\s*vertical/)
  }
})

test('Juejin clubs page renders pin club plaza from the new-pages menu', () => {
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const pageSource = readFileSync(new URL('../src/views/juejinClubs/index.vue', import.meta.url), 'utf8')
  const juejinConstantsSource = readFileSync(new URL('../src/constants/juejin.ts', import.meta.url), 'utf8')
  const liveDataConstantsSource = readFileSync(new URL('../src/constants/liveData.ts', import.meta.url), 'utf8')
  const packageSource = readFileSync(new URL('../package.json', import.meta.url), 'utf8')
  const cacheScriptSource = readFileSync(new URL('../scripts/generate-juejin-clubs-cache.mts', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/juejin-clubs'[\s\S]*?name:\s*'JuejinClubs'/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/juejin-clubs'/)
  assert.match(noticeSource, /command="\/juejin-clubs">💬 掘金圈子广场/)
  assert.match(pageSource, /<h1>圈子广场<\/h1>/)
  assert.match(juejinConstantsSource, /JUEJIN_CLUB_TOPIC_REC_API = '\/api-juejin\/tag_api\/v1\/topic\/list_by_rec'/)
  assert.match(juejinConstantsSource, /JUEJIN_CLUB_TOPIC_ALL_API = '\/api-juejin\/tag_api\/v1\/query_topic_list'/)
  assert.match(juejinConstantsSource, /JUEJIN_CLUB_TOPIC_CATEGORY_API = '\/api-juejin\/tag_api\/v1\/topic\/list_by_cate_cursor'/)
  assert.match(juejinConstantsSource, /JUEJIN_CLUB_TOPIC_SEARCH_API = '\/api-juejin\/tag_api\/v1\/topic\/list_by_search_cursor'/)
  assert.match(liveDataConstantsSource, /JUEJIN_CLUBS_CACHE_FILE = 'juejin-clubs-cache\.json'/)
  assert.match(pageSource, /clubsCacheUrl = buildLiveDataUrl\(JUEJIN_CLUBS_CACHE_FILE\)/)
  assert.match(juejinConstantsSource, /label:\s*'技术'[\s\S]*?label:\s*'互动交流'[\s\S]*?label:\s*'职场'[\s\S]*?label:\s*'吃喝玩乐'/)
  assert.match(juejinConstantsSource, /label:\s*'许愿池'[\s\S]*?label:\s*'情感'[\s\S]*?label:\s*'掘金一下'/)
  assert.match(pageSource, /class="club-grid"/)
  assert.match(pageSource, /class="popular-clubs"[\s\S]*?人气圈子/)
  assert.match(pageSource, /popularTopicTitles[\s\S]*?'上班摸鱼'[\s\S]*?'青训营-快乐出发'[\s\S]*?'树洞一下'[\s\S]*?'技术交流圈'[\s\S]*?'内推招聘广场'/)
  assert.match(pageSource, /async function fetchAllTopics\(\): Promise<void>/)
  assert.match(pageSource, /width:\s*min\(100%,\s*1500px\)/)
  assert.match(pageSource, /grid-template-columns:\s*minmax\(0,\s*1160px\)\s*420px/)
  assert.match(pageSource, /grid-template-columns:\s*repeat\(2,\s*minmax\(420px,\s*520px\)\)/)
  assert.match(pageSource, /justify-content:\s*center/)
  assert.match(pageSource, /formatCount\(item\.topic\.follower_count\)[\s\S]*?掘友[\s\S]*?formatCount\(item\.topic\.msg_count\)[\s\S]*?沸点/)
  assert.match(juejinConstantsSource, /buildJuejinClubUrl\(topicId\?: string\)/)
  assert.match(packageSource, /generate-juejin-course-cache\.mts && node scripts\/generate-juejin-clubs-cache\.mts && node scripts\/generate-boss-city-cache\.mts && vite build/)
  assert.match(cacheScriptSource, /publicCachePath[\s\S]*?public[\s\S]*?LIVE_DATA_DIR[\s\S]*?JUEJIN_CLUBS_CACHE_FILE/)
  assert.match(cacheScriptSource, /topic\/list_by_rec/)
  assert.match(cacheScriptSource, /query_topic_list/)
  assert.match(cacheScriptSource, /topic\/list_by_cate_cursor/)
  assert.match(cacheScriptSource, /topic\/list_by_search_cursor/)
})

test('Juejin signin page renders the daily check-in calendar from the new-pages menu', () => {
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const pageSource = readFileSync(new URL('../src/views/juejinSignin/index.vue', import.meta.url), 'utf8')
  const juejinConstantsSource = readFileSync(new URL('../src/constants/juejin.ts', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/juejin-signin'[\s\S]*?name:\s*'JuejinSignin'/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/juejin-signin'/)
  assert.match(noticeSource, /command="\/juejin-signin">📅 掘金每日签到/)
  assert.match(juejinConstantsSource, /JUEJIN_SIGNIN_URL = `\$\{JUEJIN_SITE_BASE_URL\}\/user\/center\/signin\?from=sign_in_menu_bar`/)
  assert.match(pageSource, /<h1>每日签到<\/h1>/)
  assert.match(pageSource, /签到规则/)
  assert.match(pageSource, /补签卡：/)
  assert.match(pageSource, /立即签到/)
  assert.match(pageSource, /宜朝西编程/)
})

test('BOSS Zhipin Hangzhou page recreates the homepage search jobs and company sections', () => {
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const pageSource = readFileSync(new URL('../src/views/bossZhipinHangzhou/index.vue', import.meta.url), 'utf8')
  const bossConstantsSource = readFileSync(new URL('../src/constants/bossZhipin.ts', import.meta.url), 'utf8')
  const liveDataConstantsSource = readFileSync(new URL('../src/constants/liveData.ts', import.meta.url), 'utf8')
  const bossServiceSource = readFileSync(new URL('../src/services/bossZhipin.ts', import.meta.url), 'utf8')
  const storageKeysSource = readFileSync(new URL('../src/constants/storageKeys.ts', import.meta.url), 'utf8')
  const packageSource = readFileSync(new URL('../package.json', import.meta.url), 'utf8')
  const proxySource = readFileSync(new URL('../config/viteProxy.ts', import.meta.url), 'utf8')
  const resolverSource = readFileSync(new URL('../src/utils/resolveApiUrl.ts', import.meta.url), 'utf8')
  const cacheScriptSource = readFileSync(new URL('../scripts/generate-boss-city-cache.mts', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/boss-zhipin-hangzhou'[\s\S]*?name:\s*'BossZhipinHangzhou'/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/boss-zhipin-hangzhou'/)
  assert.match(noticeSource, /command="\/boss-zhipin-hangzhou">💼 BOSS直聘杭州首页/)
  assert.match(bossConstantsSource, /BOSS_HOME_URL = `\$\{BOSS_SITE_BASE_URL\}\/hangzhou\/\?ka=header-home`/)
  assert.match(bossConstantsSource, /BOSS_MAP_URL = buildBossMapUrl/)
  assert.match(bossConstantsSource, /BOSS_CITY_API = `\$\{BOSS_PROXY_PREFIX\}\$\{BOSS_API_PATHS\.city\}`/)
  assert.match(bossConstantsSource, /BOSS_CITY_GROUP_API = `\$\{BOSS_PROXY_PREFIX\}\$\{BOSS_API_PATHS\.cityGroup\}`/)
  assert.match(bossConstantsSource, /BOSS_POSITION_API = `\$\{BOSS_PROXY_PREFIX\}\$\{BOSS_API_PATHS\.position\}`/)
  assert.match(bossConstantsSource, /BOSS_INDUSTRY_API = `\$\{BOSS_PROXY_PREFIX\}\$\{BOSS_API_PATHS\.industry\}`/)
  assert.match(bossConstantsSource, /BOSS_JOB_LIST_API = `\$\{BOSS_PROXY_PREFIX\}\$\{BOSS_API_PATHS\.jobList\}`/)
  assert.match(bossConstantsSource, /function buildBossJobDetailUrl\(/)
  assert.match(liveDataConstantsSource, /BOSS_CITY_CACHE_FILE = 'boss-city-cache\.json'/)
  assert.match(bossServiceSource, /bossCityCacheUrl = buildLiveDataUrl\(BOSS_CITY_CACHE_FILE\)/)
  assert.match(pageSource, /STORAGE_KEYS\.BOSS_SELECTED_CITY/)
  assert.match(storageKeysSource, /BOSS_SELECTED_CITY: 'HOOKSVUE_BOSS_SELECTED_CITY_V2'/)
  assert.match(pageSource, /<h1>\{\{ selectedCity\.name \}\}招聘网<\/h1>/)
  assert.match(pageSource, /class="boss-city-dialog"/)
  assert.match(pageSource, /热门城市/)
  assert.match(pageSource, /按字母选择:/)
  assert.match(pageSource, /热门职位:/)
  assert.match(pageSource, /const hotKeywords = computed<PositionCard\[\]>/)
  assert.match(pageSource, /normalizeOptionList\(positionResponse\?\.zpData\)/)
  assert.match(pageSource, /normalizeOptionList\(industryResponse\?\.zpData\)/)
  assert.match(pageSource, /class="boss-job-card"/)
  assert.doesNotMatch(pageSource, /class="boss-job-card"[\s\S]{0,160}@click="selectPosition\(job\)"/)
  assert.match(pageSource, /selectedListingMode/)
  assert.match(pageSource, /职位入口/)
  assert.match(pageSource, /相关行业/)
  assert.match(pageSource, /class="company-card"/)
  assert.doesNotMatch(pageSource, /const hotJobs:/)
  assert.doesNotMatch(pageSource, /const companies:/)
  assert.match(pageSource, /function buildSearchUrl\(keyword: string\): string \{[\s\S]*?buildBossSearchUrl\(selectedCity\.value\.code, keyword\)/)
  assert.match(pageSource, /function buildOfficialHomeUrl\(\): string \{[\s\S]*?buildBossOfficialHomeUrl\(selectedCity\.value\.code\)/)
  assert.match(pageSource, /function buildOfficialMapUrl\(\): string \{[\s\S]*?buildBossMapUrl\(/)
  assert.match(pageSource, /function selectPosition\(position: PositionCard\): void \{[\s\S]*?refreshVisibleData\(\)/)
  assert.doesNotMatch(pageSource, /locationCity[\s\S]*?selectedCity\.value/)
  assert.match(pageSource, /function refreshVisibleData\(\): Promise<void> \{[\s\S]*?fetchBossJobList\(\{[\s\S]*?cityCode: selectedCity\.value\.code[\s\S]*?positionCode: activePositionCode\(\)[\s\S]*?industryCode: selectedIndustry\.value\?\.code[\s\S]*?sortType: listingModeSortType\(\)/)
  assert.match(pageSource, /function requestBrowserLocationCity\(\): void \{[\s\S]*?navigator\.geolocation\.getCurrentPosition/)
  assert.match(pageSource, /function resolvePositionDetailUrl\(position: PositionCard\): Promise<string> \{[\s\S]*?fetchBossJobList/)
  assert.match(pageSource, /function openPosition\(position: PositionCard\): Promise<void> \{[\s\S]*?about:blank/)
  assert.match(pageSource, /function selectIndustry\(industry: IndustryCard\): void \{[\s\S]*?refreshVisibleData\(\)/)
  assert.match(pageSource, /function selectListingMode\(mode: ListingMode\): void \{[\s\S]*?refreshVisibleData\(\)/)
  assert.match(pageSource, /function openMapPage\(\): void \{[\s\S]*?path: '\/boss-zhipin-hangzhou-map'[\s\S]*?city: String\(selectedCity\.value\.code\)/)
  assert.match(pageSource, /if \(!isCityModalOpen\.value \|\| !selectedProvinceCode\.value\) \{[\s\S]*?syncProvincePickerWithCity\(selectedCity\.value\)/)
  assert.match(packageSource, /generate-juejin-clubs-cache\.mts && node scripts\/generate-boss-city-cache\.mts && vite build/)
  assert.match(proxySource, /'\/api-boss': createProxyEntry\('\/api-boss', 'https:\/\/www\.zhipin\.com'/)
  assert.match(resolverSource, /'\/api-boss': 'https:\/\/www\.zhipin\.com'/)
  assert.match(cacheScriptSource, /publicCachePath[\s\S]*?public[\s\S]*?LIVE_DATA_DIR[\s\S]*?BOSS_CITY_CACHE_FILE/)
  assert.match(cacheScriptSource, /BOSS_API_PATHS\.city/)
  assert.match(cacheScriptSource, /BOSS_API_PATHS\.cityGroup/)
  assert.match(cacheScriptSource, /BOSS_API_PATHS\.position/)
  assert.match(cacheScriptSource, /BOSS_API_PATHS\.industry/)
  assert.match(appSource, /<AlapiBottomMusicPlayer v-if="isDyFormRoute" \/>/)
})

test('BOSS Zhipin Hangzhou map page renders local map jobs and official map links', () => {
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')
  const pageSource = readFileSync(new URL('../src/views/bossZhipinHangzhouMap/index.vue', import.meta.url), 'utf8')
  const bossConstantsSource = readFileSync(new URL('../src/constants/bossZhipin.ts', import.meta.url), 'utf8')
  const mockSource = readFileSync(new URL('../src/views/bossZhipinHangzhouMap/mock.ts', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/boss-zhipin-hangzhou-map'[\s\S]*?name:\s*'BossZhipinHangzhouMap'/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?'\/boss-zhipin-hangzhou-map'/)
  assert.match(noticeSource, /command="\/boss-zhipin-hangzhou-map">🗺️ BOSS直聘地图找工作/)
  assert.match(bossConstantsSource, /BOSS_MAP_URL = buildBossMapUrl/)
  assert.match(pageSource, /<h1>地图找工作<\/h1>/)
  assert.match(pageSource, /class="hangzhou-map"/)
  assert.match(pageSource, /class="map-pin"/)
  assert.match(pageSource, /class="map-job-card"/)
  assert.match(pageSource, /const keyword = ref<string>\(String\(route\.query\.query \|\| ''\)\)/)
  assert.match(pageSource, /function selectedPositionCode\(\): number \| undefined/)
  assert.match(pageSource, /function selectedIndustryCode\(\): number \| undefined/)
  assert.match(pageSource, /function selectQuickFilter\(filter: string\): void \{[\s\S]*?fetchMapJobs\(\)/)
  assert.match(pageSource, /fetchBossJobList\(\{[\s\S]*?cityCode: selectedCityCode\.value[\s\S]*?positionCode,[\s\S]*?industryCode,/)
  assert.match(pageSource, /selectedFilter\.value === '全部' \? '' : selectedFilter\.value[\s\S]*?job\.skills/)
  assert.match(pageSource, /fetchBossMetaEndpoints/)
  assert.match(pageSource, /fetchBossCityCache\(\)/)
  assert.match(pageSource, /selectedCityName[\s\S]*?核心区/)
  assert.match(pageSource, /fallbackJobs = computed<MapJob\[\]>/)
  assert.match(mockSource, /Java开发工程师/)
  assert.match(mockSource, /前端开发工程师/)
  assert.match(mockSource, /西湖区/)
  assert.match(mockSource, /滨江区/)
  assert.doesNotMatch(pageSource, /aria-label="杭州职位地图"/)
  assert.match(pageSource, /function buildOfficialJobUrl\(job: MapJob\): string \{[\s\S]*?buildBossMapUrl\(/)
})

test('LOLM page renders official news categories and expanded fields', () => {
  const pageSource = readFileSync(new URL('../src/views/lolm/index.vue', import.meta.url), 'utf8')
  const styleSource = readFileSync(new URL('../src/views/lolm/css/index.scss', import.meta.url), 'utf8')
  const apiSource = readFileSync(new URL('../src/utils/lolmApi.ts', import.meta.url), 'utf8')

  assert.match(apiSource, /LOLM_NEWS_PATH\s*=\s*'\/api-lolm-news\/cmc\/cross'/)
  assert.match(apiSource, /serviceId:\s*'166'/)
  assert.match(apiSource, /source:\s*'web_pc'/)
  assert.match(pageSource, /activeNewsIndex\s*=\s*ref<number>\(2\)/)
  assert.match(pageSource, /name:\s*'新闻'[\s\S]*?tags:\s*'113538'/)
  assert.match(pageSource, /name:\s*'版本'[\s\S]*?tags:\s*'119437'/)
  assert.match(pageSource, /name:\s*'公告'[\s\S]*?tags:\s*'113539'/)
  assert.match(pageSource, /name:\s*'社区'[\s\S]*?tags:\s*'113542,113541'/)
  assert.match(pageSource, /name:\s*'赛事'[\s\S]*?tags:\s*'117878,117877,17483,118344'/)
  assert.match(pageSource, /limit:\s*officialNewsPageSize/)
  assert.match(pageSource, /<el-select[\s\S]*?v-model="officialNewsPage"[\s\S]*?filterable[\s\S]*?@change="changeOfficialNewsPage"/)
  assert.match(pageSource, /officialNewsPageOptions\s*=\s*computed<number\[\]>/)
  assert.match(pageSource, /class="hero-card-grid"/)
  assert.match(pageSource, /selectedHero/)
  assert.match(pageSource, /开始吧/)
  assert.match(pageSource, /buildHeroDetailUrl\(hero: HeroRankItem\)[\s\S]*?detail\.html\?heroid=/)
  assert.match(pageSource, /copyHeroDetailLink/)
  assert.match(styleSource, /\.hero-card-grid\s*\{[\s\S]*?grid-template-columns:\s*repeat\(5,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(styleSource, /\.oat-btn\s*\{/)
  assert.match(pageSource, /展开全部字段/)
  assert.match(pageSource, /getNewsRawFields\(news\.raw\)/)
})

test('Production mobile visits are routed to an H5 desktop-link copy page', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const h5Source = readFileSync(new URL('../src/views/h5DesktopLink/index.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/h5\/:ticket'/)
  assert.match(routerSource, /import\.meta\.env\.PROD/)
  assert.match(routerSource, /isMobileLikeClient/)
  assert.match(routerSource, /path:\s*`\/h5\/\$\{buildH5Ticket\(to\)\}`/)
  assert.match(routerSource, /query:\s*\{[\s\S]*?target:\s*to\.fullPath/)
  assert.match(routerSource, /hasAllowedMobilePageAccess/)
  assert.match(appSource, /routeViewPaths:[\s\S]*?\/h5/)
  assert.match(appSource, /isH5DesktopHintRoute/)
  assert.match(h5Source, /复制链接/)
  assert.match(h5Source, /电脑端链接/)
  assert.match(h5Source, /front_end_navigation_allow_mobile_page/)
  assert.match(h5Source, /navigator\.clipboard\.writeText/)
})

test('Bilibili Live Area Tag pages and Baidu Trending pages have direct routes, toolbox entries, and configured area IDs', () => {
  const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
  const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
  const toolboxSource = readFileSync(new URL('../src/views/toolbox/index.vue', import.meta.url), 'utf8')
  const noticeSource = readFileSync(new URL('../src/components/BrowserSupportNotice.vue', import.meta.url), 'utf8')

  const virtualView = readFileSync(new URL('../src/views/bilibiliLiveVirtual/index.vue', import.meta.url), 'utf8')
  const entertainmentView = readFileSync(new URL('../src/views/bilibiliLiveEntertainment/index.vue', import.meta.url), 'utf8')
  const radioView = readFileSync(new URL('../src/views/bilibiliLiveRadio/index.vue', import.meta.url), 'utf8')
  const chatView = readFileSync(new URL('../src/views/bilibiliLiveChat/index.vue', import.meta.url), 'utf8')
  const knowledgeView = readFileSync(new URL('../src/views/bilibiliLiveKnowledge/index.vue', import.meta.url), 'utf8')
  const playTogetherView = readFileSync(new URL('../src/views/bilibiliLivePlayTogether/index.vue', import.meta.url), 'utf8')

  const baiduMainView = readFileSync(new URL('../src/views/baiduTrending/index.vue', import.meta.url), 'utf8')
  const baiduMovieView = readFileSync(new URL('../src/views/baiduMovie/index.vue', import.meta.url), 'utf8')
  const baiduNovelView = readFileSync(new URL('../src/views/baiduNovel/index.vue', import.meta.url), 'utf8')
  const baiduTeleplayView = readFileSync(new URL('../src/views/baiduTeleplay/index.vue', import.meta.url), 'utf8')

  assert.match(routerSource, /path:\s*'\/bilibili-live-virtual'/)
  assert.match(routerSource, /path:\s*'\/bilibili-live-entertainment'/)
  assert.match(routerSource, /path:\s*'\/bilibili-live-radio'/)
  assert.match(routerSource, /path:\s*'\/bilibili-live-chat'/)
  assert.match(routerSource, /path:\s*'\/bilibili-live-knowledge'/)
  assert.match(routerSource, /path:\s*'\/bilibili-live-play-together'/)

  assert.match(routerSource, /path:\s*'\/baidu-trending'/)
  assert.match(routerSource, /path:\s*'\/baidu-trending-movie'/)
  assert.match(routerSource, /path:\s*'\/baidu-trending-novel'/)
  assert.match(routerSource, /path:\s*'\/baidu-trending-teleplay'/)

  assert.match(appSource, /\/bilibili-live-virtual/)
  assert.match(appSource, /\/bilibili-live-play-together/)
  assert.match(appSource, /\/baidu-trending-movie/)
  assert.match(appSource, /\/baidu-trending-novel/)
  assert.match(appSource, /\/baidu-trending-teleplay/)

  assert.match(toolboxSource, /id:\s*'bilibili-live-play-together'/)
  assert.match(toolboxSource, /id:\s*'baidu-trending-movie'/)
  assert.match(toolboxSource, /id:\s*'baidu-trending-novel'/)
  assert.match(toolboxSource, /id:\s*'baidu-trending-teleplay'/)

  const itemBlockSource = readFileSync(new URL('../src/components/WebLibraryItemBlock.vue', import.meta.url), 'utf8')

  assert.match(noticeSource, /command:\s*'\/bilibili-live-play-together'/)
  assert.match(noticeSource, /command:\s*'\/baidu-trending-movie'/)
  assert.match(noticeSource, /command:\s*'\/baidu-trending-novel'/)
  assert.match(noticeSource, /command:\s*'\/baidu-trending-teleplay'/)
  assert.match(noticeSource, /children:\s*\[/)
  assert.match(itemBlockSource, /web-library-sub-items/)

  assert.match(virtualView, /:parent-area-id="9"/)
  assert.match(entertainmentView, /:parent-area-id="1"/)
  assert.match(radioView, /:parent-area-id="5"/)
  assert.match(chatView, /:parent-area-id="14"/)
  assert.match(knowledgeView, /:parent-area-id="11"/)
  assert.match(playTogetherView, /:parent-area-id="301"/)

  assert.match(baiduMainView, /tabMetaMap/)
  assert.match(baiduMovieView, /tab="movie"/)
  assert.match(baiduNovelView, /tab="novel"/)
  assert.match(baiduTeleplayView, /tab="teleplay"/)
})

